# Lobby do PurpleMC
# purplemc.net

database:
  host: "localhost"
  port: 3306
  database: "purplemc"
  username: "root"
  password: ""
  ssl: false
  connection-timeout: 30000

lobby:
  spawn:
    world: "world"
    x: 0.0
    y: 100.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0